# Generated by Django 4.2.6 on 2023-10-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_firmenname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firmenname',
        ),
    ]
