# Generated by Django 4.2.6 on 2023-10-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_neuetabelle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeueTabelle',
        ),
    ]
