# Generated by Django 4.2.6 on 2023-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_neuetabelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('firmenname', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('postleitzahl', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=255)),
                ('land', models.CharField(max_length=255)),
            ],
        ),
    ]
