# Generated by Django 4.2.6 on 2023-10-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_registrationmodeldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailcode', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='registrationmodeldata',
            name='emailverification',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrationmodeldata',
            name='endofdemo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
