# Generated by Django 4.2.6 on 2023-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingIntervalls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interval', models.IntegerField(max_length=15)),
            ],
        ),
    ]
