# Generated by Django 4.2.6 on 2023-11-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_pricing_besitzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='billingintervalls',
            name='interval',
            field=models.IntegerField(),
        ),
    ]
