# Generated by Django 4.2.6 on 2023-11-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pricing_status_alter_billingintervalls_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kat',
            field=models.CharField(default='', max_length=255),
        ),
    ]
