# Generated by Django 4.2.6 on 2023-11-07 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_item_kat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='erstellungsdatum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
