# Generated by Django 4.2.6 on 2023-11-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_pricing_erstellungsdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='nameofabo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
