# Generated by Django 4.2.6 on 2023-12-05 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_pricing_nameofabo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('besitzer', models.IntegerField()),
                ('preis', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('abrechnungsdatum', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='kategories',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='rechnungsintervall',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.AddField(
            model_name='examplecontract',
            name='kategories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kategorie'),
        ),
        migrations.AddField(
            model_name='abo',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kategorie'),
        ),
        migrations.AddField(
            model_name='abo',
            name='rechnungsintervall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.billingintervalls'),
        ),
    ]
