# Generated by Django 4.2.6 on 2023-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_abo_examplecontract_kategorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abo',
            name='preis',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
