# Generated by Django 4.2.6 on 2023-12-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_blob',
            field=models.BinaryField(),
        ),
    ]
