# Generated by Django 4.2.6 on 2023-12-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_imagemodel_image_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='owner',
            field=models.IntegerField(default=0),
        ),
    ]
