# Generated by Django 4.2.6 on 2023-12-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_imagemodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='aboid',
            field=models.IntegerField(default=0),
        ),
    ]
