# Generated by Django 4.2.6 on 2023-12-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_imagemodel_aboid'),
    ]

    operations = [
        migrations.AddField(
            model_name='abo',
            name='imageid',
            field=models.IntegerField(default=0),
        ),
    ]
