# Generated by Django 4.2.6 on 2024-01-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_abo_mailnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abo',
            name='mailnotification',
        ),
        migrations.AddField(
            model_name='companydata',
            name='mailnotification',
            field=models.BooleanField(default=True),
        ),
    ]
