# Generated by Django 4.2.3 on 2024-01-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_abo_mailnotification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmodeldata',
            old_name='endofdemo',
            new_name='sub_value',
        ),
    ]
