# Generated by Django 4.2.3 on 2024-01-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_endofdemo_registrationmodeldata_sub_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmodeldata',
            old_name='sub_value',
            new_name='subvalue',
        ),
    ]
