# Generated by Django 4.2.3 on 2024-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_sub_value_registrationmodeldata_subvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodeldata',
            name='stripe_subscription_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
