# Generated by Django 4.2.10 on 2024-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_registrationmodeldata_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodeldata',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
