# Generated by Django 4.2.10 on 2024-02-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_registrationmodeldata_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
    ]
