# Generated by Django 4.2.10 on 2024-05-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_companydata_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
    ]
