# Generated by Django 4.2.10 on 2024-05-12 17:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_emailcode_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='userid',
            field=models.IntegerField(verbose_name=api.models.User),
        ),
    ]
